### ISSUE TITLE
Incorrect MIME type on files served by PsychicHTTP.

### ISSUE THREAD

**Issue by tomikaka22** [BCsabaEngine/svelteesp32#33]
HI Csaba 🇭🇺 ! I'm not sure if I should be opening an issue here, or on the PsychicHTTP project repo.

I am building a web app in Sveltekit that I'm going to serve from the esp32. The problem is, browsers complain about incorrect MIME types set on some ".js" files.

The project works with https://github.com/me-no-dev/ESPAsyncWebServer, it only does this when I use the project with the `-e psychic` flag. When creating the C++ header file from the sveltekit default npx project, it works, the HTTP response headers' content type attribute is set correctly. Which leads me to believe that I am doing something in sveltekit that svelteesp32/PsychicHTTP doesn't like.

![Screenshot From 2024-12-05 16-08-48](https://github.com/user-attachments/assets/466be64b-369f-4821-bc6d-6a0b90f027a8)
![Screenshot From 2024-12-05 15-58-49](https://github.com/user-attachments/assets/c9eb0f20-b1cc-4e2e-adfc-6842f9e4d4c6)
![Screenshot From 2024-12-05 15-57-09](https://github.com/user-attachments/assets/f3395111-da10-4fa8-abfe-2722c96b10dd)

**Comment by BCsabaEngine** [comment]
Hello Tamas!

Psychic uses the built-in ESP IDF http lib. It's supposedly a bit faster, but it depends more on what IDF version you're using: directly or indirectly, for example via platformIO.

The issue could be IDF or psychic level. The good news is that it works fine with async!

I need help and you can help me. I think the error can be caused consistently, so it's an excellent field for testing. I would like you to try the following steps by modifying the generated source code, it's **enough to do it for one file**:
- replace application/javascript with the standard **text/javascript**
- use this instead of setContentType: addHeader("Content-Type", "text/javascript")
- Remove the ETag-related test, don't bother me.

Use a few CTRL+R to see what data and header psychic returns.

**If you have the opportunity to try these, it would be a big step forward. Please let me know if you experience anything!**

ps: There is a v2 version of psychic, currently available on the DEV branch. You can still experiment with it, we are already prepared for it (-e psychic2). But I think we will find a solution with psychic1 as well.

**Comment by tomikaka22** [comment]
Thanks for the swift response!
I am new to c++ programming, but I will do my best to help!

I am using the Arduino IDE, latest 2.3.4 appimage.

I rebuilt the sveltekit project, made the edits you requested (i think) and uploaded it to my esp32.
Nothing seems to have changed. I only made the edits seen in the screenshot.

![Screenshot From 2024-12-05 20-57-11](https://github.com/user-attachments/assets/bded2f49-8cbf-4188-befd-caf0cb8d4060)
![Screenshot From 2024-12-05 20-56-01](https://github.com/user-attachments/assets/e892fc74-e758-4a70-a596-d89e243ecbe8)

**Comment by BCsabaEngine** [comment]
Thank you for your cooperation. It looks like everything is ok, but every files are served as an empty file without headers. Strange.

Tomorrow I will pick up an esp32 and I will test it with similar filenames, sizes, etc. We will learn from it.

**Comment by BCsabaEngine** [comment]
If I click, the main document (/) is successfully served with ESP, is there only a problem with the JS files?

**Comment by BCsabaEngine** [comment]
Have you tried SHIFT+reload button?

Please try to display one of JS file directly, so copy js file url path in browser url bar. Try to show the js content without app.

**Comment by tomikaka22** [comment]
Yes, i have tried shift reloading, and the devtools has a check mark to disable caching, I have that enabled as well.
I have added a favicon, accessing it with http://192.168.0.31/favicon.png works, Content-Type: image/png

Accessing a .js file directly results in "index.html" being served instead. Weird.
Trying http://192.168.0.31/index.html yields "index.html" as well.

I threw together a zip file if you want to look around, it reproduces the error.
I cut up my project as to not share the whole thing, so it's non functional but it at least reproduces the errors I am seeing.
https://www.mediafire.com/file/0xckrc0ux37e67j/PsychicHTTP-header-error.zip/file

**Comment by tomikaka22** [comment]
But as you said, it's probably best to investigate tomorrow, it's getting late. :)

**Comment by BCsabaEngine** [comment]
I have downloaded your code. I have quickly initialized a platformio project with your source code and the situation is same, only html file and favicon served by http server. But after a small change I arrived to this state: 
![image](https://github.com/user-attachments/assets/590524ff-2ad9-4d28-909b-dd207b9c4a9f)

**Comment by tomikaka22** [comment]
Nice! Did you figure out what went wrong?

**Comment by BCsabaEngine** [comment]
Unfortunately (I don't know for what reason), psychicHttp does not handle .on() event handlers dynamically.

Since there are 44 files in the generated code, and psychicHttp is (by default) only prepared for 20 files, you must specify that it can handle more files.

Change the code below to make it work:
```
  initWiFi();
  server.config.max_uri_handlers = 60; //can be 50 too, but do not forget later with more files
  server.listen(80);
  initSvelteStaticFiles(&server);
```

I thought about whether the generated code can do this, but unfortunately it has to be set quite early, much earlier than the generated code runs. And I don't know what value it should be set to, because there may be other handlers. So it will just give you a hint of what the minimum value should be.

So, you just paste the one line above and continue trying the application.

**Comment by BCsabaEngine** [comment]
Now I delete you source files and project, thank you for your trust, you shared code with me.

**Comment by BCsabaEngine** [comment]
And please let me know if it works :)

**Comment by BCsabaEngine** [comment]
We have released a new version (https://github.com/BCsabaEngine/svelteesp32/releases/tag/v1.5.2) to include minimal value as comment is generated code. Only when psychic used (async and psychic2 use without it).

**Comment by tomikaka22** [comment]
Thank you for the help! It looks to be working now.
Are there any downsides to just setting the max uri handlers to a large value and just forgetting about it?

**Comment by BCsabaEngine** [comment]
Larger value uses some unused pointer (about 4 bytes). I think, you should set it to 100 and think about it, if your project gone too large.
